### PR TITLE
Reconnect

### PR DESCRIPTION
**Pull request by mcdonnelldean**
Taken from #86 updating to ensure travis tests are passing (they weren't)

### CODE REVIEW

**Comment by mcdonnelldean** [comment]
0.12.0 upwards is failing with the error below.

```
Test script errors:
Multiple callbacks or thrown errors received in test "transport Basic Transport for type tcp should execute three consecutive calls" (done)
      at tryOnImmediate (timers.js:534:15)
      at processImmediate [as _immediateCallback] (timers.js:514:5)
There were 1 test script error(s).
Failed tests:
  24) transport Basic Transport for type tcp should execute three consecutive calls:
      connect ECONNREFUSED 127.0.0.1:10201
      at Object.exports._errnoException (util.js:890:11)
      at exports._exceptionWithHostPort (util.js:913:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1059:14)
```

0.10.x is completely flatlining all over the place.

**Comment by mcdonnelldean** [comment]
Looks like a bug in the client logic in tcp, bit more investigating.

**Comment by mcdonnelldean** [comment]
Going to revert this change as @mcollina needs the seneca 2.0 stuff for error changes. @mcollina I'll revert the PR to the point where the tests pass and then merge.

**Comment by mcdonnelldean** [comment]
Closed in favour of #90 which includes tests but not modifications.

**Comment by vladgolubev** [comment]
Are the tests ok already, so we can proceed with this PR?

**Pull request closed without merging**
