### PR TITLE
Reworking TCP

### PR DESCRIPTION
**Pull request by geek**
Looking for a review.

Removed dependency on reconnect, fixing issue when a server or client die and it resends data.  

Fixes https://github.com/senecajs/seneca/issues/318

Please note that this is dependent on a bugfix in seneca 2.0.1 being published

### CODE REVIEW

**Comment by mcdonnelldean** [comment]
@geek Had a look over, looks good.

**Comment by StarpTech** [comment]
@geek here are my recommendations:

- we could respect this issue https://github.com/hapijs/hapi/pull/3014 to improve the performance of JSON.stringify
- we could respect circular references in JSON (instead to throw an exception) to improve availibility.

Best solution: Use http://msgpack.org/ to stream JSON lover network. It is very easy to connect.

everything else is fine thank you.

**Comment by mcdonnelldean** [comment]
@geek @StarpTech Moved to #87 as I am having a look into it. There are travis failures from the changes. Once these are green I will merge.

**Comment by mcdonnelldean** [comment]
@StarpTech So the implementation in #87 has regression issues on client idempotency. It will be a little while longer before this is baked. Couple of days and I should have it licked.

**Comment by StarpTech** [comment]
@thanks for the update I will follow this.

**Pull request closed without merging**
